CREATE TABLE users (
    id MEDIUMINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(256) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL,
    email VARCHAR(256) NOT NULL,
    superuser BOOLEAN DEFAULT 0,
    staff BOOLEAN DEFAULT 0,
    enable BOOLEAN DEFAULT 1,
    PRIMARY KEY (id)
)
